spring.application.name=23_Redis_Examaple
spring.data.redis.url=redis-13123.c305.ap-south-1-1.ec2.redns.redis-cloud.com
spring.data.redis.password=awERNX3LBo6JzcrVo6AxVxJXFwuKgxdA
spring.data.redis.port=13123
spring.data.redis.username=default